import os

# from q8s.enums import Target
from q8s.project import CacheNotBuiltException, Project, ProjectNotFoundException

from importlib.metadata import entry_points


def extract_non_none_value(arr):
    """
    Extract the first non-None value from a list

    Used to get the first available configuration value from multiple
    sources generated by job plugins
    """
    non_none_values = [x for x in arr if x is not None]
    return non_none_values[0] if non_none_values else None


def get_docker_image(target: str = None, logging=None):
    try:
        project = Project()
        key = target
        image = project.cached_images(target=key)

    except ProjectNotFoundException as e:
        if logging:
            logging.warning(e)
        image = os.environ.get("DOCKER_IMAGE", "vstirbu/benchmark-deps")
    except CacheNotBuiltException as e:
        if logging:
            logging.warning(e)
        image = os.environ.get("DOCKER_IMAGE", "vstirbu/benchmark-deps")
    except Exception as e:
        if logging:
            logging.error(f"Error loading project: {e}")
            logging.warning("Q8Sproject file not found in current folder")
        image = os.environ.get("DOCKER_IMAGE", "vstirbu/benchmark-deps")

    return image


def get_kubeconfig(kubeconfig=None):
    if kubeconfig:
        return kubeconfig

    try:
        project = Project()
        return project.kubeconfig
    except ProjectNotFoundException:
        return None


def get_available_targets():
    available = []

    for ep in entry_points(group="q8s.targets"):
        try:
            plugin_cls = ep.load()
            plugin = plugin_cls()
            if hasattr(plugin, "target_name"):
                available.append(plugin.target_name)
        except Exception:
            pass

    return available